apiVersion: v1
kind: Secret
metadata:
  name: workercontagemsecret
type: Opaque
data:
  ConnectionSqlServer: <CONNECTION STRING DO SQL SERVER EM BASE64>
  UsernameKafka: $ConnectionString
  PasswordKafka: <CONNECTION STRING DO AZURE EVENT HUBS EM BASE64>
  SaslKafka: plaintext
  TlsKafka: enable
  AppInsightsConnection: <CONNECTION STRING DO APPLICATION INSIGHTS EM BASE64>