apiVersion: apps/v1
kind: Deployment
metadata:
  name: workercontagem
spec:
  selector:
    matchLabels:
      app: workercontagem
  replicas: 1
  template:
    metadata:
      labels:
        app: workercontagem
    spec:
      containers:
      - name: workercontagem
        image: renatogroffe/workercontagem-appinsightsconnstring-kafka-dotnet6:latest
        env:
        - name: ApacheKafka__Topic
          value: topic-contagem
        - name: ApacheKafka__GroupId
          value: workercontagem
        - name: ApacheKafka__Host
          value: resource.servicebus.windows.net:9093
        - name: ConnectionStrings__ApplicationInsights
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: AppInsightsConnection
        - name: ApacheKafka__Username
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: UsernameKafka
        - name: ApacheKafka__Password
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: PasswordKafka              
        - name: ConnectionStrings__BaseContagem
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: ConnectionSqlServer